name: CI for Cypress tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  cypress:
    runs-on: macOS
    steps:
      - name: Download repository
        uses: actions/checkout@v4
        
      - name: Download NodeJS
        uses: actions/setup-node@v4.0.2

      - name: Install dependencies
        run: npm install
  
      
      - name: Run Cypress tests
        run: npm run cypress:run

      - name: Archive test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: cypress/reports/html/
