# This is a basic workflow to help you get started with Actions

name: CI for Cypress tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cypress:
    name: Test
    runs-on: ubuntu-latest
    steps:
    
      - name: Setup Node.js environment and run Cypress tests
      - uses: actions/setup-node@v4.0.2
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
      - run: npm install
      - run: npm run cypress:run
      - run: npm run start_app


      - name: Archive test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: cypress/reports/html/
